apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-05-16T14:38:07Z"
  labels:
    app: taxonium-backend
  name: taxonium-backend-deployment
  namespace: default
  resourceVersion: "298145"
  uid: 83cfe171-281d-4077-a610-2b6592ed14fb
spec:
  clusterIP: 10.152.183.36
  clusterIPs:
  - 10.152.183.36
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 8000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: taxonium-backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
